version: '{build}'
clone_depth: 10
environment:
  matrix:
    - appveyor_build_worker_image: Visual Studio 2022
      JAVA_HOME: C:\Program Files\Java\jdk17
init:
  - cmd: SET PATH=%JAVA_HOME%\bin;%PATH%
install:
  - cmd: SET MAVEN_OPTS=-Xmx4g
  - cmd: SET JAVA_OPTS=-Xmx4g
  - cmd: mvn --version
  - cmd: java -version
build_script:
  - mvn clean package -B -DskipTest
test_script:
  - mvn clean package -B
cache:
  - C:\Users\appveyor\.m2
artifacts:
  - path: target\Regionerator.jar
    name: Regionerator
branches:
  only:
    - master
only_commits:
  files:
    - src/**/*
    - pom.xml
    - appveyor.yml
