# This is the Regionerator configuration file.
# For more information about options, please see the wiki:
#   https://github.com/Jikoo/Regionerator/wiki/Configuration
#

# Every x seconds, chunks around each player online are flagged.
# Flags prevent deletion for a configurable amount of time, allowing
# players to prevent areas from being deleted simply by being active.
#
# Default values cause a 9x9 chunk (144x144 blocks) around players to be
# flagged every 10 seconds. This means that unless players exceed a travel
# speed of 14.4 m/s chunks will be continuously flagged as they pass.
# For more information on travel speeds, please check the Minecraft wiki.
# https://minecraft.gamepedia.com/Transportation#Methods
flagging:
  seconds-per-flag: 10
  # Square around each player's current chunk to flag. 0 = current chunk only.
  chunk-flag-radius: 4
  # Chunks are automatically flagged as visited when generated.
  # If true, the flag is set to a special value that will be overwritten once
  # a player actually visits the area. This allows you to reduce load by
  # pre-generating area for exploration and not deleting unvisited areas.
  # Note that flagging must be enabled in worlds (days-till-flag-expires > 0).
  flag-generated-chunks-until-visited: true

# Don't mess with the cache settings unless you know what you're doing and
# are having problems. Larger servers may want to tweak these values to reduce
# GC churn or memory usage.
cache:
  # Seconds between expiration. Longer reduces churn but decreases accuracy of other cache settings.
  minimum-expiration-frequency: 10
  # Minutes to cache values for. Increase to reduce churn, decrease to reduce memory usage.
  retention: 10
  # Maximum number of entries per batch update.
  maximum-batch-size: 1024
  # Milliseconds between batch updates.
  batch-delay: 500
  # Maximum number of cached entries. Increase to reduce churn, decrease to reduce memory usage.
  max-cache-size: 640000

deletion:
  # Set deletion to be paused on startup.
  start-paused: false
  # Recovery time in milliseconds between expensive operations.
  # Recovery time is always waited between region checks.
  deletion-recovery-time: 250
  # Number of chunks with expensive checks between recovery delays.
  # Values >= 1024 cause no additional recovery time.
  expensive-checks-between-recovery: 128
  # Hours between deletion cycles
  hours-between-cycles: 12
  # Whether to remember time for next cycle on plugin load
  remember-next-cycle-time: false

# Worlds the plugin is able to delete regions in
worlds:
  # "default" applies to all worlds not specified.
  default:
    # Flags older than x days can be ignored and the region deleted.
    # Set to -1 to disable Regionerator in a world.
    # To disable flagging, set this to 0.
    # days-till-flag-expires must be greater than 0 to be used with delete-new-unvisited-chunks
    days-till-flag-expires: -1

# Hooks to attempt to check for protections from.
# If your protection plugin of choice isn't here, ask!
hooks:
  BentoBox: true
  Civs: true
  ClaimChunk: true
  Factions: true
  GriefDefender: true
  GriefPrevention: true
  Lands: true
  PlotSquared: true
  PreciousStones: true
  RedProtect: true
  Residence: true
  Towny: true
  WorldGuard: true
  VanillaSpawnProtection: true

# Debug-level enables more and more verbose logging of actions as increased.
# OFF - no debug messages
# LOW - Minimal debug messages, periodic deletion reports
# MEDIUM - More debug messages. Causes lots of spam but can help you resolve startup issues.
# HIGH - Lots of debug messages. Don't enable this unless you have a serious issue - excessive logging causes lag.
debug-level: LOW

# Please don't mess with this, you may lose settings. Controls automatic updates to config layout.
config-version: 2
