name: Auto-merge Dependabot PRs

on:
  pull_request_target

jobs:
  auto-approve:
    runs-on: ubuntu-latest
    steps:
      - name: Wait for build success
        run: sleep 60
      - name: autoapprove
        if: github.actor == 'dependabot[bot]'
        uses: hmarr/auto-approve-action@v2.0.0
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
      - name: automerge
        uses: "pascalgn/automerge-action@v0.12.0"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          MERGE_LABELS: "dependencies,automerge"
          MERGE_METHOD: "squash"
