name: Auto-merge Dependabot PRs

on:
  pull_request_target

jobs:
  auto-approve:
    runs-on: ubuntu-latest
    steps:
      - name: Wait for build success
        uses: fountainhead/action-wait-for-check@v1.0.0
        id: wait-for-build
        if: github.actor == 'dependabot[bot]'
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          checkName: 'Build Java 8'
          ref: ${{ github.event.pull_request.head.sha || github.sha }}
      - name: autoapprove
        if: github.actor == 'dependabot[bot]' && steps.wait-for-build.outputs.conclusion == 'success'
        uses: hmarr/auto-approve-action@v2.0.0
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
      - name: automerge
        uses: "pascalgn/automerge-action@v0.12.0"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          MERGE_LABELS: "dependencies"
          MERGE_METHOD: "squash"
